# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo make install FORCE_INSTALL=true
      - run: make env lint test
  make-macos:
    timeout-minutes: 30
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: sudo chown -R "$(whoami)" /usr/local
      - run: |
          for c in make bash grep; do
            brew install "${c}" --overwrite
            echo "$(brew --prefix)/opt/${c}/libexec/gnubin" >> "$GITHUB_PATH"
          done
      - run: sudo make install FORCE_INSTALL=true
      - run: make env lint test
